const godModeList = [
  {
    name: "Xenoverse",
    version: "v1.4.5",
    lastUpdated: "22-05-2022",
    linkPrimary: "https://exe.io/RKmMSy4A",
    linkSecondary: "https://stfly.me/tZBWNBh",
  },
  {
    name: "Iberia",
    version: "v2.04",
    lastUpdated: "30-03-2022",
    linkPrimary: "https://exe.io/aTxw4ceL",
    linkSecondary: "https://stfly.me/pgWAYIjKC",
  },
  {
    name: "Enigma",
    version: "v1.5",
    lastUpdated: "28-03-2022",
    linkPrimary: "https://exe.io/iQRKoyL",
    linkSecondary: "https://stfly.me/Jz6s4",
  },
  {
    name: "Red Lion",
    version: "v0.1.5",
    lastUpdated: "16-03-2022",
    linkPrimary: "https://exe.io/qkCXtfV",
    linkSecondary: "https://stfly.me/dBboqP",
  },
  {
    name: "Regalia",
    version: "v0.8",
    lastUpdated: "14-03-2022",
    linkPrimary: "https://exe.io/CAuxQ",
    linkSecondary: "https://stfly.me/iHMDCCZ",
  },
  {
    name: "Uncensored",
    version: "v1.0.3",
    lastUpdated: "10-03-2022",
    linkPrimary: "https://exe.io/Ko1Yx7",
    linkSecondary: "https://stfly.me/ivDv1wM",
  },
  {
    name: "Detergent",
    version: "v1.4.1",
    lastUpdated: "10-03-2022",
    linkPrimary: "https://exe.io/Y7Fx",
    linkSecondary: "https://stfly.me/DBn3pI",
  },
  {
    name: "Edge Rising",
    version: "v9-19-17",
    lastUpdated: "10-03-2022",
    linkPrimary: "https://exe.io/YCC9jetC",
    linkSecondary: "https://stfly.me/ivzBN",
  },
  {
    name: "Nebula",
    version: "v1.07.7",
    lastUpdated: "08-03-2022",
    linkPrimary: "https://exe.io/GN9Io",
    linkSecondary: "https://stfly.me/SLzf",
  },
  {
    name: "Godra Remastered",
    version: "v2.0",
    lastUpdated: "08-03-2022",
    linkPrimary: "https://exe.io/UZOM",
    linkSecondary: "https://stfly.me/lFYrpL",
  },
  {
    name: "Astra Adventures",
    version: "???",
    lastUpdated: "08-03-2022",
    linkPrimary: "https://exe.io/VVeZI",
    linkSecondary: "https://stfly.me/w9M8",
  },
  {
    name: "Etherean Dreams",
    version: "v2.0b",
    lastUpdated: "08-03-2022",
    linkPrimary: "https://exe.io/HbShZ8",
    linkSecondary: "https://stfly.me/zGn3d",
  },
  {
    name: "Heads & Tails",
    version: "v22.05.2021",
    lastUpdated: "15-02-2022",
    linkPrimary: "https://exe.io/JuvSI",
    linkSecondary: "https://stfly.me/scRensqvl",
  },
  {
    name: "Fantasy",
    version: "v2.4",
    lastUpdated: "02-02-2022",
    linkPrimary: "https://exe.io/ZT0Axm0",
    linkSecondary: "https://stfly.me/ggcM0ARFk",
  },
  {
    name: "Wack",
    version: "17-10-2021",
    lastUpdated: "29-01-2022",
    linkPrimary: "http://exe.io/leM4J",
    linkSecondary: "https://stfly.io/t0PhwNR",
  },
  {
    name: "Sage",
    version: "v2.0.6.1",
    lastUpdated: "27-01-2022",
    linkPrimary: "https://exe.io/fPKwan",
    linkSecondary: "https://stfly.me/CO0Mbw",
  },
  {
    name: "HGSS: Sevii Islands",
    version: "v3.3",
    lastUpdated: "23-01-2022",
    linkPrimary: "https://exe.io/C86HX",
    linkSecondary: "https://stfly.me/wE4Cp05g",
  },
  {
    name: "Myth",
    version: "v1.8.2",
    lastUpdated: "23-01-2022",
    linkPrimary: "https://exe.io/x8PZ7rNo",
    linkSecondary: "https://stfly.me/olGBFXHI",
  },
  {
    name: "Sunday",
    version: "v2.8.17",
    lastUpdated: "20-01-2022",
    linkPrimary: "https://exe.io/xcGSjT",
    linkSecondary: "https://stfly.me/3C1pqye",
  },
  {
    name: "Fire Ash",
    version: "v2.28",
    lastUpdated: "18-01-2022",
    linkPrimary: "https://exe.io/RPlogG",
    linkSecondary: "https://stfly.me/VzvCc4Iak",
  },
  {
    name: "Legends of the Arena",
    version: "v1.4.1",
    lastUpdated: "14-01-2022",
    linkPrimary: "https://exe.io/DzbahlJk",
    linkSecondary: "https://stfly.me/kKfdu",
  },
  {
    name: "Project Royal",
    version: "v1.4.4",
    lastUpdated: "10-01-2022",
    linkPrimary: "https://exe.io/z1Jnvo",
    linkSecondary: "https://stfly.me/3s0CuFRiQ",
  },
  {
    name: "Project Revival",
    version: "v1.1.6",
    lastUpdated: "07-01-2022",
    linkPrimary: "https://exe.io/ZAtSMwFK",
    linkSecondary: "https://stfly.me/ijdxu",
  },
  {
    name: "Infinity",
    version: "v2.0.4",
    lastUpdated: "06-01-2022",
    linkPrimary: "https://exe.io/A08rX9",
    linkSecondary: "https://stfly.me/FUhkS8qn8",
  },
  {
    name: "Empire",
    version: "v5.5",
    lastUpdated: "25-11-2021",
    linkPrimary: "https://exe.io/RMjZ0B7",
    linkSecondary: "https://stfly.me/Wx6M",
  },
  {
    name: "Sardonyx",
    version: "v2.8.6",
    lastUpdated: "25-10-2021",
    linkPrimary: "http://exe.io/GKxRyH",
    linkSecondary: "https://stfly.io/jnmj",
  },
  {
    name: "Empyrean",
    version: "v1.1",
    lastUpdated: "24-10-2021",
    linkPrimary: "http://exe.io/jvNLe6Kg",
    linkSecondary: "https://stfly.io/EuUP",
  },
  {
    name: "Infinite Fusion",
    version: "v4.9.1",
    lastUpdated: "14-10-2021",
    linkPrimary: "http://exe.io/MehMFBol",
    linkSecondary: "https://stfly.io/8DrToizHk",
  },
  {
    name: "Aureolin",
    version: "v1.4",
    lastUpdated: "10-10-2021",
    linkPrimary: "https://exe.io/ck29X",
    linkSecondary: "https://stfly.me/HWuF8",
  },
  {
    name: "Aster Violet",
    version: "v1.59.210901",
    lastUpdated: "10-10-2021",
    linkPrimary: "https://exe.io/IcRXv",
    linkSecondary: "https://stfly.me/oelhlf",
  },
  {
    name: "Moss Lime",
    version: "v1.03.210901",
    lastUpdated: "09-10-2021",
    linkPrimary: "https://exe.io/3GZ1lTUa",
    linkSecondary: "https://stfly.me/KKM6teYJ",
  },
  {
    name: "Coral Lapis",
    version: "v1.03.210901",
    lastUpdated: "09-10-2021",
    linkPrimary: "https://exe.io/ly2tMODe",
    linkSecondary: "https://stfly.me/4OgD5EidL",
  },
  {
    name: "Rejuvenation",
    version: "v13.0.5",
    lastUpdated: "28-09-2021",
    linkPrimary: "http://exe.io/asIB",
    linkSecondary: "https://stfly.io/sows",
  },
  {
    name: "Nova",
    version: "v2.2.1",
    lastUpdated: "19-09-2021",
    linkPrimary: "https://exe.io/z0Ku",
    linkSecondary: "https://stfly.me/QLH6N5X7",
  },
  {
    name: "Ditto Edition",
    version: "v1.3.6",
    lastUpdated: "19-09-2021",
    linkPrimary: "https://exe.io/Mhfm0",
    linkSecondary: "https://stfly.me/8kRPnRG4u",
  },
  {
    name: "Blue & White",
    version: "???",
    lastUpdated: "18-09-2021",
    linkPrimary: "https://exe.io/nX12i",
    linkSecondary: "https://stfly.me/8l880i",
  },
  {
    name: "Retold",
    version: "v2.1",
    lastUpdated: "18-09-2021",
    linkPrimary: "https://exe.io/Rd6pNby",
    linkSecondary: "https://stfly.me/PsyBq",
  },
  {
    name: "Jade",
    version: "v3.21",
    lastUpdated: "04-09-2021",
    linkPrimary: "https://exe.io/E0RZh",
    linkSecondary: "https://stfly.me/XmGwr",
  },
  {
    name: "Project Maple",
    version: "v1.3.3",
    lastUpdated: "04-09-2021",
    linkPrimary: "https://exe.io/3qNt70M",
    linkSecondary: "https://stfly.me/Hm20x3Sv",
  },
  {
    name: "Bushido",
    version: "v1.1.12",
    lastUpdated: "29-08-2021",
    linkPrimary: "https://exe.io/hiCt3",
    linkSecondary: "https://stfly.me/I4TX9a3n",
  },
  {
    name: "Soulstones",
    version: "v2.0.4",
    lastUpdated: "28-08-2021",
    linkPrimary: "https://exe.io/MbWTd",
    linkSecondary: "https://stfly.me/PRjKZoeQY",
  },
  {
    name: "Blossom of the Soul",
    version: "v1.3.0",
    lastUpdated: "02-08-2021",
    linkPrimary: "https://exe.io/wOe6fQF",
    linkSecondary: "https://stfly.me/NGpAYkm",
  },
  {
    name: "Tri-Master",
    version: "HJK-DE",
    lastUpdated: "23-07-2021",
    linkPrimary: "http://exe.io/Ytid2O",
    linkSecondary: "https://stfly.me/lGBWiX",
  },
  {
    name: "Ethereal Gates",
    version: "v1.1.1",
    lastUpdated: "24-01-2021",
    linkPrimary: "https://exe.io/Tofz",
    linkSecondary: "https://stfly.me/i1lPf6cDR",
  },
  {
    name: "Green Remix",
    version: "v18e",
    lastUpdated: "20-01-2021",
    linkPrimary: "https://exe.io/pvEltJZE",
    linkSecondary: "https://stfly.me/XDbJmZs",
  },
  {
    name: "Full Moon",
    version: "Episode 11",
    lastUpdated: "22-11-2020",
    linkPrimary: "https://exe.io/Qox0",
    linkSecondary: "https://stfly.me/DdyOT",
  },
  {
    name: "Daybreak",
    version: "v1.6.1.2",
    lastUpdated: "12-10-2020",
    linkPrimary: "http://exe.io/UjQpeAwk",
    linkSecondary: "https://stfly.me/CqM4a9YG",
  },
  {
    name: "Gemstone",
    version: "???",
    lastUpdated: "04-09-2020",
    linkPrimary: "http://exe.io/nYP1sqD1",
    linkSecondary: "https://stfly.me/4wRD",
  },
  {
    name: "Camry Legend",
    version: "31-12-2019",
    lastUpdated: "05-09-2020",
    linkPrimary: "http://exe.io/zYhay3",
    linkSecondary: "https://stfly.me/lIfLUIt2F",
  },
  {
    name: "Camry Legend 2",
    version: "14-01-2020",
    lastUpdated: "05-09-2020",
    linkPrimary: "http://exe.io/zvsIQ",
    linkSecondary: "https://stfly.me/8wI2K",
  },
  {
    name: "Alchemist",
    version: "v5.0",
    lastUpdated: "15-10-2020",
    linkPrimary: "http://exe.io/BBxX",
    linkSecondary: "https://stfly.me/CZPH3Tp0J",
  },
  {
    name: "Clockwork",
    version: "v1.9.0",
    lastUpdated: "18-08-2020",
    linkPrimary: "https://exe.io/a73gScot",
    linkSecondary: "https://stfly.me/SWV82",
  },
  {
    name: "Infinity (Juan Wagner)",
    version: "v23.03.19",
    lastUpdated: "13-08-2020",
    linkPrimary: "http://exe.io/1dHBgxF",
    linkSecondary: "https://stfly.me/IGiBUNGi",
  },
  {
    name: "Black Cinder",
    version: "???",
    lastUpdated: "05-12-2019",
    linkPrimary: "http://exe.io/zxO2MwJ7",
    linkSecondary: "https://stfly.io/CAhpg",
  },
  {
    name: "Apex",
    version: "Alpha 9.3p",
    lastUpdated: "18-01-2021",
    linkPrimary: "https://exe.io/MI03",
    linkSecondary: "https://stfly.me/YjTxH0v",
  },
  {
    name: "Spectrum",
    version: "v1.4.3",
    lastUpdated: "28-07-2020",
    linkPrimary: "http://exe.io/p4DSr3WE",
    linkSecondary: "https://stfly.me/X9x8O",
  },
  {
    name: "Solar Light Lunar Dark",
    version: "v1.0.1",
    lastUpdated: "08-05-2019",
    linkPrimary: "http://exe.io/ezHvmH4",
    linkSecondary: "https://stfly.me/RFFUco",
  },
  {
    name: "Zeta",
    version: "???",
    lastUpdated: "22-01-2019",
    linkPrimary: "http://exe.io/ZasKN4pr",
    linkSecondary: "https://stfly.me/YsNzNVN",
  },
  {
    name: "Omicron",
    version: "???",
    lastUpdated: "22-01-2019",
    linkPrimary: "http://exe.io/IMbAzw",
    linkSecondary: "https://stfly.me/NFp1h",
  },
  {
    name: "Floral Tempus",
    version: "Episode 4",
    lastUpdated: "31-10-2020",
    linkPrimary: "http://exe.io/CtLuc2v",
    linkSecondary: "https://stfly.me/PE5qUfkGu",
  },
  {
    name: "Spork",
    version: "Episode 8",
    lastUpdated: "17-01-2021",
    linkPrimary: "https://exe.io/sxgoJDZ",
    linkSecondary: "https://stfly.me/godspork",
  },
  {
    name: "Desolation",
    version: "v5.1",
    lastUpdated: "09-07-2020",
    linkPrimary: "http://exe.io/jLfR4Qh",
    linkSecondary: "https://stfly.me/pEkWsVA",
  },
  {
    name: "Alabaster",
    version: "v0.6.4",
    lastUpdated: "01-07-2020",
    linkPrimary: "http://exe.io/OqGT",
    linkSecondary: "https://stfly.me/GsF4n",
  },
  {
    name: "Rejuvenation Where Love Lies",
    version: "???",
    lastUpdated: "26-05-2020",
    linkPrimary: "http://exe.io/wioI",
    linkSecondary: "https://stfly.io/Mu4R",
  },
  {
    name: "Insurgence",
    version: "v1.2.7",
    lastUpdated: "12-06-2020",
    linkPrimary: "http://exe.io/rx82mF",
    linkSecondary: "https://stfly.io/lD9iCzI",
  },
  {
    name: "Reborn",
    version: "v18.4.1",
    lastUpdated: "03-01-2021",
    linkPrimary: "https://exe.io/godreborn",
    linkSecondary: "https://stfly.me/godreborn",
  },
  {
    name: "Uranium",
    version: "v1.2.4",
    lastUpdated: "22-01-2019",
    linkPrimary: "http://exe.io/aYFPTRJu",
    linkSecondary: "https://stfly.io/0q4f9tT",
  },
  {
    name: "Mega Adventures",
    version: "v1.2.2",
    lastUpdated: "05-04-2020",
    linkPrimary: "http://exe.io/uNWbr",
    linkSecondary: "https://stfly.io/UE4D6NmVP",
  },
  {
    name: "Fusion Generation",
    version: "???",
    lastUpdated: "29-03-2020",
    linkPrimary: "http://exe.io/16efs6KZ",
    linkSecondary: "https://stfly.io/EcwnEROF",
  },
  {
    name: "Fusion Generation 2",
    version: "???",
    lastUpdated: "29-03-2020",
    linkPrimary: "https://exe.io/jhptlJi",
    linkSecondary: "https://stfly.me/xtIW",
  },
];

export default godModeList;
